# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bc6a4d8d258abe2859a8db443e0bedcd6d2828b4b18b9c359f28bedf98e06055d9c82fb53dd605ffb06d686c216415bfa40242034ffca99504caede105e4c10

test:
  secret_key_base: a20db631705775e357c9e0012ace7cebf6a1e4613da46dc60ffcf0c8b0f352a28b63574c4194239ffb10f52c66abedb874b8923d7e21819c460d0bd75ea9aea5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
